# Theoretical Questions
1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

ans. Numpy is the most powerful library for numerical computing. It provides support for large multi dimensional arrays and matrices.
# Advantage of NumPy


*   NumPy operations are implemented in C programming language, making faster than equivalent operations.
*   NumPy arrays are stored in contiguous blocks of memory making them faster execution of codes.


*   Mathematical Computation is fast.

overall, Numpy enhance python's cabailities for numerical operation by introducing ndarray, a powerful n-dimension array object and it includes functions for array operations, linear algebra, statistics, and more, turning Python into a robust platform for scientific computing.






In [ ]:
#example of NumPy array
import numpy as np
#create an array of large number.
large_number = np.random.random(1000000)
#calculate the mean value using NumPy
mean_value = np.mean(large_number)
#printing the mean value
print(f"Mean value: {mean_value}")

Mean value: 0.49968878688897717


In [ ]:
#taking 3*3 matrix using radom value between 1 to 4(excluding).
arr1 = np.random.randint(1,4,(3,3) , dtype = int)
arr2 = np.random.randint(1,4,(3,3), dtype = int)
#printing the matrix
print("Matrix 1")
print(arr1)
print("\n Matrix 2")
print(arr2)

print("\nMatrix multiplication")
result = arr1 @ arr2
#printing the result of matrix multiplication
print(result)

Matrix 1
[[2 2 1]
 [3 3 1]
 [1 2 2]]

 Matrix 2
[[1 3 2]
 [1 1 1]
 [3 1 3]]

Matrix multiplication
[[ 7  9  9]
 [ 9 13 12]
 [ 9  7 10]]



2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

ans. 'np.mean()' is a simple function used to calculate arithmetic means along a axis while other side 'np.average()' is more flexible than 'np.mean()' used for calculating weighted average.


In [ ]:
#syntax of 'np.mean()'
#np.mean(variable_used, axis = none , dtype= none)

#syntax of 'np.average()'
#np.average(variable_used, axis = none , weights = none , dtype= none)


In [ ]:
#example of 'np.mean()'
lis = [1,2,3,4,5]
print(np.mean(lis))

3.0


In [ ]:
#example of 'np.average()'
lis = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
print(np.average(lis, weights=weights))

3.0


#When to use 'np.mean' and 'np.average'




*   Use np.mean():

When you need a simple, unweighted average of an array or along a specified axis.

*   Use np.average():



When you need to calculate a weighted average.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

ans. Reversing an array means changing the order of elements so that the first element becomes the last, the second becomes the second last, and so on. NumPy provides several ways to reverse arrays along different axes.

In [ ]:
#Reversing 1D array

#using slicing
lis = np.array([1,2,3,4,5])
print(lis[::-1])

#using flip()
lis = np.array([1,2,3,4,5])
print(np.flip(lis))



[5 4 3 2 1]
[5 4 3 2 1]


In [ ]:
#Reversing 2D array

#using flip() function
lis = np.array([[1,2,3],[4,5,6],[6,7,8], [9,10,11]])
print(lis)
#reversed List along row
print("\nReversing 2D array along row:")
flip_lis = np.flip(lis , axis = 0)
print(flip_lis)

#reversed List along column side
print("\nReversing 2D array along column:")
flip_lis = np.flip(lis , axis = 1)
print(flip_lis)
#using

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]

Reversing 2D array along row:
[[ 9 10 11]
 [ 6  7  8]
 [ 4  5  6]
 [ 1  2  3]]

Reversing 2D array along column:
[[ 3  2  1]
 [ 6  5  4]
 [ 8  7  6]
 [11 10  9]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

ans. In NumPy, you can determine the data type of elements in an array using 'dtype' attribute. This attribute help in providing the type of data.



In [ ]:
import numpy as np

#creating an element of integer element
std_grade = np.array([40,60,70,80,45], dtype = int)
print(std_grade)
print(std_grade.dtype)

#creating an element of float
std_grade1 = np.array([40,56,34,23,77], dtype = float)
print(std_grade)
print(std_grade.dtype)

[40 60 70 80 45]
int64
[40 60 70 80 45]
int64


The importance of data types in memory management and performance is given below:
## Memory Management:
 Different data types occupy different storage in memory location just like int32 store 4 bytes of memory while int64 stores 8 bytes of memory. Choosing the appropriate datatype can save significant amount of memory, especially while dealing with large dataset.

## performance:
Generally, operations on smaller data types requires fewer cpu cycles.For instance, performaning arithematic operation on 'int32' is faster than on 'int64' types.


In [ ]:
#array of int32
arr_int32 = np.random.randint(1,4,(3,5), dtype = np.int32)
print(arr_int32)
print(arr_int32.dtype)
print('\n')
#array of int64
arr_int64 = np.random.randint(1,4,(3,5), dtype = np.int64)
print(arr_int64)
print(arr_int64.dtype)

[[1 2 3 2 3]
 [2 2 2 1 1]
 [2 3 2 2 2]]
int32


[[3 3 2 3 1]
 [1 3 1 3 3]
 [1 2 1 3 3]]
int64


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


ans. In NumPy, ndarrays is the most powerful n- dimensional array used for doing scientific calculation.An ndarray's is a set of table of elements(usually number) of same data type, indexed by tuple of non negative numbers.The number of dimensions is also known as rank of the array, is specified by the shape of array. In comparision to standard python list, ndarray takes less time to execute code.



In [ ]:
import numpy as np

#creating 1-d array
arr_1d = np.array([1,2,3,4,5,6])
print(f' 1-d array: \n {arr_1d}')
print('\n')
#creating 2-d array
arr_2d = np.array([[1,2,3], [8,9,10]])
print(f' 2-d array: \n {arr_2d}')

 1-d array: 
 [1 2 3 4 5 6]


 2-d array: 
 [[ 1  2  3]
 [ 8  9 10]]


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ans. NumPy arrays store homogenous data types so it store in a contigous memory location which allows for efficient memory use for fast computations and improve cache performance and access speed.Support vectorized operations, allowing element-wise operations to be performed without explicit loops. This leverages low-level optimizations in C. While python lis are rely's on python's built in function, which are slower amd less optimized for numerical computation.


In [ ]:
import numpy as np
import time

#creating large arrays and list
large_list = list(range(1000000))
large_array = np.arange(1000000)

#measure time for sum operation on list
start = time.time()
sum_list = sum(large_list)
end = time.time()
print(f"sum of list: {sum_list} ,time taken by list: {end-start} s")

#measure time for sum of operation on numpy arrays
start = time.time()
sum_array = np.sum(large_array)
end = time.time()
print(f"sum of array: {sum_array}, time taken by array:{end-start} s")



sum of list: 499999500000 ,time taken by list: 0.01182246208190918 s
sum of array: 499999500000, time taken by array:0.0013785362243652344 s


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

ans.


*   vstack() : vstack() function stack array vertically from first axis (0 axis). It can be thought as stacking from top of each other.




In [5]:
import numpy as np
#example of vstack() function
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
result = np.vstack((arr1,arr2))
print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


*   hstack() : hstack() functions stack array horizontally from second axis (1 axis). It can be thought as concatinating array side by side.

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
result = np.hstack((arr1,arr2))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

ans. The main difference between fliplr() and flipud() methods in NumPy are:


*   fliplr(): This methods helps to flip array from left to right effectively reversing the order of column from second axis(1 axis) and does't affect row.


In [19]:
#2d array
arr1 = np.array([[1,2,3],[6,7,8],[9,8,10]])
print(arr1)
print('\n')
#fliplr() method
print('flipping method for 2d array \n')
flip_arr1 = np.fliplr(arr1)

print(flip_arr1)

[[ 1  2  3]
 [ 6  7  8]
 [ 9  8 10]]


flipping method for 2d array 

[[ 3  2  1]
 [ 8  7  6]
 [10  8  9]]


flipud(): This methods helps to flip array from up to down effectively reversing the order of rows from first axis(0 axis) and does't affect column.

In [68]:
arr2 = np.random.randint(1,5,(3,4))
print('original array:')
print(arr2)
print('\n')

#fliplr() method
print('flipping method for 2d array \n')
flip_arr2 = np.flipud(arr2)
print(flip_arr2)


original array:
[[2 4 2 1]
 [3 2 4 2]
 [4 1 1 1]]


flipping method for 2d array 

[[4 1 1 1]
 [3 2 4 2]
 [2 4 2 1]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ans. The functionality of the array_splits method in array are:

*   It splits the array and number of parts or indices at which the split should occur. The axis along which to split. The default is 0 (along rows for 2D arrays).


In [23]:
#syntax of array_split()
# numpy.array_split(array, indices_or_sections, axis=0)

#handling uneven splits
When the array cannot be split evenly into the specified number of sections, array_split() ensures that the sub-arrays have nearly equal size by distributing the remainder among the front slices.

In [28]:

arr1 = np.arange(15)
splits = np.array_split(arr1 , 3 , axis = 0)
for split in splits:
  print(split)


[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [36]:
arr1 = np.random.randint(1,5,(3,3))
splits = np.array_split(arr1 , 3 , axis = 1)
for split in splits:
  print(split)



[[4]
 [2]
 [1]]
[[4]
 [2]
 [2]]
[[1]
 [1]
 [1]]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

ans. Vectorization is the process of performing operations on entire arrays or large sections of arrays without using explicit loops. This approach leverages NumPy's internal C and Fortran routines, making computations much faster and more efficient than equivalent Python loops.

In [50]:
#with out vectorization
arr = np.array([1,2,3,4,5])
result = []
for x in arr:
  result.append(x ** 3)

print(f"without vectorization: {result} \n")

#with vectorization

result = arr ** 3
print(f"with vectorization: {result} \n")


without vectorization: [1, 8, 27, 64, 125] 

with vectorization: [  1   8  27  64 125] 



#Broadcating
Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. Broadcasting involves automatically expanding the dimensions of smaller arrays to match the dimensions of larger arrays.

In [53]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2],[3]])
result = arr1 + arr2
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [59]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


#Practical Questions:
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [75]:
arr = np.random.randint(1,100,(3,3))
print('original array')
print(arr)
print()
#interchanging row using flipud() method
row_flip = np.flipud(arr)
print(f"Interchanging rows : \n {row_flip} \n")

#interchanging columns using fliplr() method
column_flip = np.fliplr(arr)
print(f"Interchanging columns : \n {column_flip} \n")

#using transpose
transpose_arr = arr.T
print(f"Interchanging columns into rows: \n {transpose_arr} \n")


original array
[[44  8 74]
 [71 58 62]
 [23 72 39]]

Interchanging rows : 
 [[23 72 39]
 [71 58 62]
 [44  8 74]] 

Interchanging columns : 
 [[74  8 44]
 [62 58 71]
 [39 72 23]] 

Interchanging columns into rows: 
 [[44 71 23]
 [ 8 58 72]
 [74 62 39]] 



2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [85]:
arr = np.arange(10)
print("original array with 10 elements:")
print(arr)

#reshaping into 2*5 array
reshaped_arr1 = arr.reshape(2,5)
print("\nReshaping into 2*5 array:")
print(reshaped_arr1)

#reshaping into 5*2 array
reshaped_arr2 = arr.reshape(5,2)
print("\nReshaping into 5*2 array:")
print(reshaped_arr2)


original array with 10 elements:
[0 1 2 3 4 5 6 7 8 9]

Reshaping into 2*5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaping into 5*2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [139]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.randint(1,10, (4, 4))

print("Original 4x4 array:")
print(array_4x4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, 1)

print("\nResulting 6x6 array with border of zeros:")
print(array_6x6)

Original 4x4 array:
[[3 2 6 5]
 [1 8 5 3]
 [1 1 7 3]
 [4 1 8 4]]

Resulting 6x6 array with border of zeros:
[[0 0 0 0 0 0]
 [0 3 2 6 5 0]
 [0 1 8 5 3 0]
 [0 1 1 7 3 0]
 [0 4 1 8 4 0]
 [0 0 0 0 0 0]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [86]:
arr = np.arange(10,60,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.


In [91]:
arr_str = np.array(['python', 'numpy','pandas'])
#Upper case in array of strings
arr_str_upper = np.char.upper(arr_str)
print(arr_str_upper)

#lower case in array of strings
arr_str_lower = np.char.lower(arr_str)
print(arr_str_lower)

#title case in array of strings
arr_str_title = np.char.title(arr_str)
print(arr_str_title)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


In [93]:
# Create a NumPy array of words
words_array = np.array(["hello", "world", "numpy", "array"])

# Function to insert a space between each character of a word
def insert_spaces(word):
    return ' '.join(word)

# Apply the function to each element in the NumPy array
spaced_words_array = np.vectorize(insert_spaces)(words_array)

print(spaced_words_array)



['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [102]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Element-wise Addition")
result = np.add(arr1,arr2)
print(result)

print("\nElement-wise Subtraction")
result = np.subtract(arr1,arr2)
print(result)

print("\n Element-wise Multiplication")
result = np.multiply(arr1,arr2)
print(result)

print("\nElement-wise Division")
result = np.divide(arr1,arr2)
print(result)

Element-wise Addition
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Element-wise Subtraction
[[0 0 0]
 [0 0 0]
 [0 0 0]]

 Element-wise Multiplication
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Element-wise Division
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


In [108]:
#creating a 5*5  identity matrix
identity_matrix = np.eye(5)
print(identity_matrix)
print('\n')

#extracting its diagonal elements
diagonal_elements = np.diag(identity_matrix)
print(diagonal_elements)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.


In [121]:
num = np.random.randint(0,1000,100)
print(num)
print('\n')

# displaying all prime numbers
for n in num:
    if n <= 1:
        print(n, "is not a prime number")
    else:
        is_prime = True

        for i in range(2, n+1):
            if (n % i) == 0:
                is_prime = False
                break
        if is_prime:
            print(n, "is a prime number")
        else:
            print(n, "is not a prime number")

[ 21 175 734 915 502 889 585 271 867 592 835 637   1 911 197 707 393 861
 409 188 623 282 691  91 730 110 662 816 530  65 625 296 337  86 804 333
 539 394 351 875 796 867 693 390 399 179 296   3 315 679 444 921 419 259
 331 741 350  78 364 939 422 144 406 922 172 759 469 776 684 879 364 138
 844 402  15  98 329 948 476 856 861 952 616 238 234 834 237 583 972 140
 709 683 464 850 535 903 563 329 976 449]


21 is not a prime number
175 is not a prime number
734 is not a prime number
915 is not a prime number
502 is not a prime number
889 is not a prime number
585 is not a prime number
271 is a prime number
867 is not a prime number
592 is not a prime number
835 is not a prime number
637 is not a prime number
1 is not a prime number
911 is a prime number
197 is a prime number
707 is not a prime number
393 is not a prime number
861 is not a prime number
409 is a prime number
188 is not a prime number
623 is not a prime number
282 is not a prime number
691 is a prime number
91 is not a prim

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [134]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month
daily_temperatures = np.random.uniform(20, 30, 30)  # 30 days in a month

print("Daily Temperatures:")
print(daily_temperatures)

# Calculate the weekly averages
weekly_temperatures = []
for temp in range(0, 30, 7):
    weekly_average = np.mean(daily_temperatures[temp:temp+7])
    weekly_temperatures.append(weekly_average)

print("\nWeekly Averages:")
print(weekly_temperatures)

Daily Temperatures:
[28.26926947 21.61242797 24.15147523 25.51141983 23.38455347 21.79817191
 24.72137689 25.99855968 22.73171141 29.08618327 27.39024165 25.3532687
 23.80695092 20.71910002 26.65291992 23.58793151 26.16825382 25.34019958
 26.96139326 20.89700014 25.48974535 20.65222703 26.40719663 20.67386985
 25.92469684 21.25598226 28.46813756 29.02499356 24.60183321 27.41849159]

Weekly Averages:
[24.20695639653535, 25.012287949127813, 25.01392051289963, 24.629586247854007, 26.010162399328827]
